/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131318",
        "surface-dim": "#131318",
        "surface-bright": "#39383e",
        "surface-container-lowest": "#0e0e13",
        "surface-container-low": "#1b1b20",
        "surface-container": "#1f1f25",
        "surface-container-high": "#2a292f",
        "surface-container-highest": "#35343a",
        "surface-variant": "#35343a",
        "on-surface": "#e4e1e9",
        "on-surface-variant": "#ccc3d8",
        "inverse-surface": "#e4e1e9",
        "inverse-on-surface": "#303036",
        outline: "#958da1",
        "outline-variant": "#4a4455",
        "surface-tint": "#d2bbff",
        primary: "#d2bbff",
        "on-primary": "#3f008e",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#732ee4",
        secondary: "#ffb0cd",
        "on-secondary": "#640039",
        "secondary-container": "#aa0266",
        "on-secondary-container": "#ffbad3",
        tertiary: "#c6c6c7",
        "on-tertiary": "#2f3131",
        "tertiary-container": "#656767",
        "on-tertiary-container": "#e5e6e6",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#ffd9e4",
        "secondary-fixed-dim": "#ffb0cd",
        "on-secondary-fixed": "#3e0022",
        "on-secondary-fixed-variant": "#8c0053",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#0a0a0f",
        "on-background": "#e4e1e9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-label": ["JetBrains Mono", "monospace"],
        display: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-label": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
